site_name: Performance Testing

site_author: Kieran wood (@descent098)
site_url: https://kieranwood.ca/performance-tests
repo_url: https://github.com/descent098/performance-tests

nav:
  - Home: index.md
  - Http-basics: http-basics/index.md
  - Source: https://github.com/descent098/performance-tests
theme:
  theme_style: dark
  components:
      site_name: true
  name: simple-blog

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True

extra_css:
  - css/overrides.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML